sync-fork:
    rules:
       - if: '$CI_COMMIT_BRANCH == "master"'
         changes:
            - README.md
            - /*
    script:
        - git remote add upstream https://gitlab.com/derpystuff/discord-asset-datamining.git
        - git fetch upstream
        - git checkout master
        - git merge upstream/master
        - git push
