sync-master:
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.password "${GITLAB_USER_PASSWORD}"
  rules:
      - if: '$CI_COMMIT_BRANCH == "master"'
        changes:
          - README.md
          - /*
  script:
    - git remote add upstream https://gitlab.com/derpystuff/discord-asset-datamining.git
    - git fetch --all
    - git switch -c master origin/master
    - git merge upstream/master
    - git push origin master
sync-organized:
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.password "${GITLAB_USER_PASSWORD}"
  rules:
      - if: '$CI_COMMIT_BRANCH == "organized"'
        changes:
          - README.md
          - /*
  script:
    - git remote add upstream https://gitlab.com/derpystuff/discord-asset-datamining.git
    - git fetch --all
    - git switch -c master origin/organized
    - git branch
    - git branch
    - git merge upstream/organized
    - git branch
    - git push origin organized
