sync-fork:
    rules:
       - if: '$CI_COMMIT_BRANCH == "master"'
         changes:
            - README.md
            - /*
    script:
      - git config user.name "Pukimaa"
      - git config user.email "pukima@pukima.site"
      - git remote add upstream https://gitlab.com/derpystuff/discord-asset-datamining.git
      - git fetch --all
      - git checkout origin/master
      - git branch
      - git branch
      - git merge upstream/master
      - git branch
      - git push origin master
