sync-master:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - mkdir ~/.ssh
    - touch ~/.ssh/known_hosts
    - ssh-keygen -R gitlab.com
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.password "${GITLAB_USER_PASSWORD}"
  rules:
      - if: '$CI_COMMIT_BRANCH == "master"'
        changes:
          - README.md
          - /*
  script:
    - git remote add upstream https://gitlab.com/derpystuff/discord-asset-datamining.git
    - git fetch --all
    - git switch -c master origin/master
    - git merge upstream/master
    - git push -o ci-skip git@gitlab.com:tako-discord/discord-asset-datamining.git HEAD:organized
sync-organized:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GIT_SSH_PRIV_KEY")
    - mkdir ~/.ssh
    - touch ~/.ssh/known_hosts
    - ssh-keygen -R gitlab.com
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.password "${GITLAB_USER_PASSWORD}"
  rules:
      - if: '$CI_COMMIT_BRANCH == "organized"'
        changes:
          - README.md
          - /*
  script:
    - git remote add upstream https://gitlab.com/derpystuff/discord-asset-datamining.git
    - git fetch --all
    - git switch -c master origin/organized
    - git branch
    - git branch
    - git merge upstream/organized
    - git branch
    - git push -o ci-skip git@gitlab.com:tako-discord/discord-asset-datamining.git HEAD:organized
